platform :ios, '10.0'
use_frameworks!
target 'ToBTapplcok' do
pod 'Kingfisher'
pod 'PKHUD'
pod 'MJRefresh'
pod 'iOSDFULibrary'
pod 'Instructions'
pod 'TOCropViewController'
pod 'CryptoSwift'
pod 'MJRefresh'
pod 'SwiftyJSON'
pod 'SwiftDate'
pod 'CFAlertViewController'
pod 'RxSwift'
pod 'RxCocoa'
pod 'NSObject+Rx'
pod 'RxDataSources'
pod 'Moya-ObjectMapper'
pod 'Moya-ObjectMapper/RxSwift'

end
